# TODO: explain it
name: Bootstrap 3 Wagon

# TODO: explain it
# subdomain: sample

# TODO: explain it
# domains: [www.example.com, example.com]

# TODO: explain it
locales: [en]

# TODO: explain it
seo_title: wagon_starter
meta_keywords: "some meta keywords"
meta_description: "some meta description"